# Generated by Django 4.2.30 on 2026-05-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0002_aidieticiansubscription_is_paid_and_more'),
        ('users', '0018_dieticianschedule_monthly_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('ai_subscription', 'AI Diyetisyen Aboneliği')], default='ai_subscription', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('success', 'Tamamlandı'), ('failed', 'Başarısız'), ('canceled', 'İptal Edildi')], default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('iyzico_token', models.CharField(blank=True, max_length=255)),
                ('iyzico_payment_id', models.CharField(blank=True, max_length=255)),
                ('iyzico_conversation_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.client')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='subscription.aidieticiansubscription')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
