# Generated by Django 4.2.29 on 2026-03-17 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.CharField(choices=[('Dietician', 'Diyetisyen'), ('Client', 'Danışan'), ('Admin', 'Admin')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Erkek'), ('Female', 'Kadın'), ('Other', 'Diğer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danışan Profili',
                'verbose_name_plural': 'Danışan Profilleri',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Dietician',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tc_no', models.CharField(max_length=11, unique=True)),
                ('tc_verified', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_document', models.FileField(blank=True, upload_to='licenses/%Y/%m/%d/')),
                ('biography', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Beklemede'), ('Accepted', 'Onaylandı'), ('Rejected', 'Reddedildi')], default='Pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diyetisyen Profili',
                'verbose_name_plural': 'Diyetisyen Profilleri',
            },
            bases=('users.user',),
        ),
    ]
