# Generated by Django 4.2.29 on 2026-03-21 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietician',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='dietician_profile_photos/'),
        ),
        migrations.CreateModel(
            name='DieticianReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.client')),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.dietician')),
            ],
            options={
                'verbose_name': 'Diyetisyen Değerlendirme',
                'verbose_name_plural': 'Diyetisyen Değerlendirmeleri',
                'ordering': ('-created_at',),
                'unique_together': {('client', 'dietician')},
            },
        ),
    ]
