# Generated by Django 4.2.29 on 2026-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_client_age_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allergies',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Alerjiler'),
        ),
    ]
