# Generated by Django 4.2.29 on 2026-03-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_dieticianassignment_activity_level_and_more'),
        ('users', '0005_client_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietplans', to='diets.dieticianassignment'),
        ),
    ]
