# Generated by Django 4.2.29 on 2026-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_client_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chronic_conditions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Kalıcı hastalıklar'),
        ),
    ]
