# Generated by Django 4.2.29 on 2026-03-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_chronic_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietician',
            name='title',
            field=models.CharField(blank=True, choices=[('DIETICIAN', 'Diyetisyen'), ('EXPERT_DIETICIAN', 'Uzman Diyetisyen'), ('INTERN_DIETICIAN', 'Stajyer Diyetisyen')], max_length=20),
        ),
    ]
