# Generated by Django 4.2.30 on 2026-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_dietician_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vejetaryan'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20)),
                ('sugar_intake', models.CharField(choices=[('NONE', 'Hiç'), ('LOW', 'Haftada 1-2 kez'), ('MEDIUM', 'Haftada 3-4 kez'), ('HIGH', 'Her gün'), ('CRAVINGS', 'Anlık gelen tatlı krizlerim var')], default='NONE', max_length=20)),
                ('activity_level', models.CharField(choices=[('NONE', 'Hiç'), ('LOW', 'Haftada 1-2 kez'), ('MEDIUM', 'Haftada 3-4 kez'), ('HIGH', 'Haftada 4-5 kez'), ('VERY_HIGH', 'Her gün')], default='NONE', max_length=20)),
                ('goal', models.CharField(choices=[('Lose', 'Kilo Vermek'), ('Gain', 'Kilo Almak'), ('Maintain', 'Formumu Korumak')], max_length=20)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_breastfeeding', models.BooleanField(default=False)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('smoking_use', models.BooleanField(default=False)),
                ('medications', models.JSONField(blank=True)),
                ('dislike_foods', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dietician',
            name='appointment_duration',
            field=models.IntegerField(choices=[(30, '30 Dakika'), (45, '45 Dakika'), (60, '60 Dakika'), (90, '90 Dakika')], default=30),
        ),
    ]
