# Generated by Django 4.2.30 on 2026-04-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_clienthealthsnapshot_dietician_appointment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthealthsnapshot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='users.client'),
        ),
    ]
