# Generated by Django 4.2.30 on 2026-04-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clienthealthsnapshot_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthealthsnapshot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_health_snapshots', to='users.client'),
        ),
    ]
