# Generated by Django 4.2.30 on 2026-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_clienthealthsnapshot_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietician',
            name='work_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietician',
            name='work_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
