# Generated by Django 4.2.30 on 2026-04-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_dietician_work_time_end_dietician_work_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='static_analysis',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Analizler'),
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
