# Generated by Django 4.2.30 on 2026-04-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_client_static_analysis_weightlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietician',
            name='appointment_duration',
        ),
        migrations.RemoveField(
            model_name='dietician',
            name='work_time_end',
        ),
        migrations.RemoveField(
            model_name='dietician',
            name='work_time_start',
        ),
        migrations.CreateModel(
            name='DieticianSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time_start', models.TimeField(blank=True, null=True)),
                ('work_time_end', models.TimeField(blank=True, null=True)),
                ('weekend_workings', models.BooleanField(default=False)),
                ('weekend_work_time_start', models.TimeField()),
                ('weekend_work_time_end', models.TimeField()),
                ('appointment_duration', models.IntegerField(choices=[(30, '30 Dakika'), (45, '45 Dakika'), (60, '60 Dakika'), (90, '90 Dakika')], default=30)),
                ('dietician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.dietician')),
            ],
        ),
    ]
