# Generated by Django 4.2.30 on 2026-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_dietician_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieticianschedule',
            name='weekend_work_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dieticianschedule',
            name='weekend_work_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dieticianschedule',
            name='work_time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dieticianschedule',
            name='work_time_start',
            field=models.TimeField(),
        ),
    ]
