# Generated by Django 4.2.30 on 2026-05-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_dieticianschedule_weekend_work_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Erkek'), ('Female', 'Kadın'), ('Other', 'Diğer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dieticianschedule',
            name='dietician',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietician_schedule', to='users.dietician'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
