# Generated by Django 4.2.30 on 2026-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_client_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthealthsnapshot',
            name='budget',
            field=models.CharField(blank=True, choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek')], max_length=20),
        ),
    ]
