# Generated by Django 4.2.30 on 2026-05-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_clienthealthsnapshot_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticianschedule',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aylık Danışmanlık Ücreti'),
        ),
    ]
