# Generated by Django 4.2.30 on 2026-05-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_dieticianschedule_monthly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietician',
            name='tc_no',
        ),
        migrations.RemoveField(
            model_name='dietician',
            name='tc_verified',
        ),
    ]
