# Generated by Django 4.2.30 on 2026-04-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dietician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('meal_type', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('calories', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='ai_dietician.aidietplan')),
            ],
            options={
                'verbose_name': 'Öğün',
                'verbose_name_plural': 'Öğünler',
                'ordering': ['id'],
            },
        ),
    ]
