# Generated by Django 4.2.30 on 2026-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dietician', '0002_aidietmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidietplan',
            name='analysis_notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
