# Generated by Django 4.2.30 on 2026-04-25 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_dietician', '0003_aidietplan_analysis_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMealChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=255)),
                ('vision_data', models.JSONField()),
                ('calorie_diff', models.FloatField()),
                ('feedback', models.TextField()),
                ('logged_at', models.DateField()),
                ('is_cheat', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_meal_checkers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
