# Generated by Django 4.2.30 on 2026-04-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dietician', '0004_aimealchecker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimealchecker',
            old_name='user_id',
            new_name='user',
        ),
    ]
