# Generated by Django 4.2.30 on 2026-05-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dietician', '0005_rename_user_id_aimealchecker_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDietMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_dietician.aidietmeal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
