# Generated by Django 4.2.30 on 2026-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dietician', '0006_aidietmealitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidietplan',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
