# Generated by Django 4.2.30 on 2026-05-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_alter_client_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDieticianSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('subscription_duration', models.CharField(choices=[('1M', '1 Ay'), ('6M', '6 Ay'), ('12M', '12 Ay')], max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_dietician_subscriptions', to='users.client')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
