# Generated by Django 4.2.29 on 2026-03-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Pazartesi'), ('Tuesday', 'Salı'), ('Wednesday', 'Çarşamba'), ('Thursday', 'Perşembe'), ('Friday', 'Cuma'), ('Saturday', 'Cumartesi'), ('Sunday', 'Pazar')], max_length=10)),
                ('total_calories', models.IntegerField()),
                ('total_proteins', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_fat', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Günlük Plan',
                'verbose_name_plural': 'Günlük Planlar',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('AI', 'Yapay Zeka Diyetisteni'), ('Dietician', 'Diyetisyen')], max_length=20)),
                ('goal', models.CharField(choices=[('Lose', 'Kilo Vermek'), ('Gain', 'Kilo Almak'), ('Maintain', 'Formumu Korumak')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Beklemede'), ('Active', 'Aktif'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], max_length=20)),
                ('start_weight', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('daily_calories', models.IntegerField()),
                ('daily_protein', models.FloatField()),
                ('daily_carbs', models.FloatField()),
                ('daily_fat', models.FloatField()),
                ('daily_water', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diyet Planı',
                'verbose_name_plural': 'Diyet Planları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Kahvaltı'), ('SnackAm', 'Kuşluk Ara Öğünü'), ('Lunch', 'Öğle Yemeği'), ('SnackPM', 'İkindi Ara Öğünü'), ('Dinner', 'Akşam Yemeği')], max_length=50)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diets.dailyplan')),
            ],
            options={
                'verbose_name': 'Öğün',
                'verbose_name_plural': 'Öğünler',
                'ordering': ['meal_type'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plan', to='diets.dietplan')),
            ],
            options={
                'verbose_name': 'Haftalık Plan',
                'verbose_name_plural': 'Haftalık Planlar',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diets.meal')),
            ],
        ),
    ]
