# Generated by Django 4.2.29 on 2026-03-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='users.client'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='dietician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to='users.dietician'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='weekly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan', to='diets.weeklyplan'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together={('diet_plan', 'week_number')},
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('daily_plan', 'meal_type')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('weekly_plan', 'day')},
        ),
    ]
