# Generated by Django 4.2.29 on 2026-03-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
        ('diets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='dietician',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='plan_type',
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='daily_calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='daily_carbs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='daily_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='daily_protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='daily_water',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='start_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Beklemede'), ('Active', 'Aktif'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='target_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DieticianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_note', models.TextField(blank=True)),
                ('dietician_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Beklemede'), ('Accepted', 'Kabul Edildi'), ('Rejected', 'Reddedildi'), ('Ended', 'Sonlandırıldı')], default='Pending', max_length=20)),
                ('assignment_type', models.CharField(choices=[('AI', 'Yapay Zeka Diyetisteni'), ('Dietician', 'Diyetisyen')], max_length=20)),
                ('goal', models.CharField(choices=[('Lose', 'Kilo Vermek'), ('Gain', 'Kilo Almak'), ('Maintain', 'Formumu Korumak')], max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='users.client')),
                ('dietician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='users.dietician')),
            ],
            options={
                'verbose_name': 'Diyetisyen Ataması',
                'verbose_name_plural': 'Diyetisyen Atamaları',
                'unique_together': {('client', 'dietician')},
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='diets.dieticianassignment'),
        ),
    ]
