# Generated by Django 4.2.29 on 2026-03-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_remove_dietplan_client_remove_dietplan_dietician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticianassignment',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Beklemede'), ('Accepted', 'Kabul Edildi'), ('Rejected', 'Reddedildi')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dieticianassignment',
            name='status',
            field=models.CharField(choices=[('Canceled', 'İptal edildi'), ('InProgress', 'Devam ediyor'), ('Ended', 'Sonlandırıldı')], default='InProgress', max_length=20),
        ),
    ]
