# Generated by Django 4.2.29 on 2026-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_dieticianassignment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieticianassignment',
            name='duration',
            field=models.CharField(choices=[('1M', '1 Ay'), ('3M', '3 Ay'), ('6M', '6 Ay'), ('12M', '1 Yıl')], max_length=20),
        ),
    ]
