# Generated by Django 4.2.29 on 2026-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_alter_dieticianassignment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticianassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dieticianassignment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Beklemede'), ('Canceled', 'İptal edildi'), ('InProgress', 'Devam ediyor'), ('Ended', 'Sonlandırıldı')], default='Pending', max_length=20, null=True),
        ),
    ]
