# Generated by Django 4.2.29 on 2026-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_dieticianassignment_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticianassignment',
            name='activity_level',
            field=models.CharField(choices=[('NONE', 'Hiç'), ('LOW', 'Haftada 1-2 kez'), ('MEDIUM', 'Haftada 3-4 kez'), ('HIGH', 'Haftada 4-5 kez'), ('VERY_HIGH', 'Her gün')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='sugar_intake',
            field=models.CharField(choices=[('NONE', 'Hiç'), ('LOW', 'Haftada 1-2 kez'), ('MEDIUM', 'Haftada 3-4 kez'), ('HIGH', 'Her gün'), ('CRAVINGS', 'Anlık gelen tatlı krizleri var')], default='NONE', max_length=20),
        ),
    ]
