# Generated by Django 4.2.29 on 2026-03-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_dieticianassignment_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyplan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
