# Generated by Django 4.2.29 on 2026-03-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0009_alter_weeklyplan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together=set(),
        ),
    ]
