# Generated by Django 4.2.29 on 2026-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0010_alter_weeklyplan_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticianassignment',
            name='alcohol_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='dietary_preference',
            field=models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vejetaryan'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='dislike_foods',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='is_breastfeeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='smoking_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dieticianassignment',
            name='sugar_intake',
            field=models.CharField(choices=[('NONE', 'Hiç'), ('LOW', 'Haftada 1-2 kez'), ('MEDIUM', 'Haftada 3-4 kez'), ('HIGH', 'Her gün'), ('CRAVINGS', 'Anlık gelen tatlı krizlerim var')], default='NONE', max_length=20),
        ),
    ]
