# Generated by Django 4.2.30 on 2026-04-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0011_dieticianassignment_alcohol_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='alcohol_use',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='dietary_preference',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='dislike_foods',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='is_breastfeeding',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='is_pregnant',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='smoking_use',
        ),
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='sugar_intake',
        ),
    ]
