# Generated by Django 4.2.30 on 2026-04-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0012_remove_dieticianassignment_activity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieticianassignment',
            name='verification_status',
        ),
    ]
