# Generated by Django 4.2.30 on 2026-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0013_remove_dieticianassignment_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='total_calories',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='total_carbs',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='total_proteins',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='protein',
        ),
        migrations.AddField(
            model_name='dieticianassignment',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Beklemede'), ('Accepted', 'Kabul Edildi'), ('Rejected', 'Reddedildi')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='week_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together={('diet_plan', 'week_number')},
        ),
    ]
