# Generated by Django 4.2.30 on 2026-05-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0014_remove_dailyplan_total_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='diets.dieticianassignment'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='diets.meal'),
        ),
    ]
