# Generated by Django 4.2.30 on 2026-05-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0015_alter_dietplan_assignment_alter_mealitem_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticianassignment',
            name='agreed_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
