# Generated by Django 4.2.29 on 2026-03-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_tr', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Besin Kategorisi',
                'verbose_name_plural': 'Besin Kategorileri',
                'ordering': ['name_tr'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_tr', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255, unique=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('OPENFOODFACTS', 'OpenFoodFacts'), ('USDA', 'USDA')], default='MANUAL', max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('calories', models.FloatField(default=0)),
                ('proteins', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='foods.foodcategory')),
            ],
            options={
                'verbose_name': 'Besin',
                'verbose_name_plural': 'Besinler',
                'ordering': ['name_tr', 'name'],
            },
        ),
    ]
