# Generated by Django 4.2.29 on 2026-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_id_alter_foodcategory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turkish', models.CharField(db_index=True, max_length=255, unique=True)),
                ('english', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Besin çevirisi',
                'verbose_name_plural': 'Besin çevirileri',
                'ordering': ('turkish',),
            },
        ),
    ]
