# Generated by Django 4.2.29 on 2026-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_foodtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
