# Generated by Django 4.2.30 on 2026-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodTranslation',
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name'], 'verbose_name': 'Besin', 'verbose_name_plural': 'Besinler'},
        ),
        migrations.RenameField(
            model_name='food',
            old_name='proteins',
            new_name='protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_description',
            field=models.CharField(default='1 Porsiyon', max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('FATSECRET', 'Fatsecret')], default='MANUAL', max_length=255),
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
